services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${CONTAINER_PORT:-8000}:80"
    working_dir: /var/www
    volumes:
      - .:/var/www